name: Build .deb package for latest Ubuntu

on:
  push:
    # tags: '*'
    ## To test, uncomment the line below with branch name used for review.
    branches: [ nx-load ]

jobs:
  build:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl]
        # See https://github.com/actions/virtual-environments
        # for the list of official distributions.
        os: [ubuntu-20.04]
      # fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:

    # Check out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install SBCL and dependencies
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y ruby ruby-dev rubygems dpkg-dev sbcl curl git-core zlib1g-dev
        sudo apt-get install -y libfixposix3 libfixposix-dev libwebkit2gtk-4.0-dev glib-networking gsettings-desktop-schemas xclip notify-osd enchant-2
        sudo apt-get install -y gobject-introspection

    - name: Build special SBCL and make package
      shell: bash
      # Don't run scripts with `sudo` since it would use /root as home instead
      # of the runner's /home/runner.
      run: ./build-scripts/build-ubuntu-package.sh

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2 # v2 is necessary for wildcards.
      ## TODO: Don't wrap deb in zip file.
      with:
        name: nyxt-ubuntu
        ## We need './' to avoid Yaml errors.
        path: ./*.deb
